In [57]:
import pandas as pd

In [79]:
df = pd.read_csv('./csv_input/07282159_modified_shapefile.csv')
community_matrix = pd.read_csv('./csv_input/Info_CSV/community_matrix.csv')
df_analysis = df.copy()

region_map = {
    'Alma Valley East': 'Capital',
    'Alma Valley West': 'Capital',
    'Highland': 'Highland',
    'Midlands': 'Lowland',
    'South East': 'Lowland',
}
df_analysis['Matrix_Region'] = df_analysis['Region'].map(region_map)

pop_type_cols = ['S', 'A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'D1', 'D2', 'E1', 'E2', 'F1', 'F2']

cm = community_matrix[['Region', 'Type', 'Code'] + pop_type_cols].rename(
    columns={'Region': 'CM_Region', 'Type': 'CM_Type', 'Code': 'CM_Code'}
)

merged = df_analysis.merge(
    cm,
    left_on=['Matrix_Region', 'Location', 'County_Type'],
    right_on=['CM_Region', 'CM_Type', 'CM_Code'],
    how='left',
)

# convert each row's per-code percentage into an actual population count
for col in pop_type_cols:
    merged[col] = merged[col] / 100.0 * merged['Population']

county_population = merged.groupby('County').agg(
    Zone=('Zone', 'first'),
    **{col: (col, 'sum') for col in pop_type_cols}
).reset_index()

county_population[pop_type_cols] = county_population[pop_type_cols].round(0).astype(int)
county_population = county_population[['County', 'Zone'] + pop_type_cols]

zone_region = df_analysis[['Zone', 'Region']].drop_duplicates().set_index('Zone')['Region']

zone_population = county_population.groupby('Zone')[pop_type_cols].sum().reset_index()
zone_population.insert(1, 'Region', zone_population['Zone'].map(zone_region))
zone_population = zone_population.sort_values('Region').reset_index(drop=True)

with pd.ExcelWriter('./analysis/population_by_type.xlsx') as writer:
    county_population.to_excel(writer, sheet_name='County', index=False)
    zone_population.to_excel(writer, sheet_name='Zone', index=False)

zone_population

,Zone,Region,S,A1,A2,B1,B2,C1,C2,D1,D2,E1,E2,F1,F2
0,Alington,Alma Valley East,144671,178455,188608,694513,117980,266298,236525,672770,90529,301677,164343,283338,50444
1,Twicken Meads,Alma Valley East,22169,56996,83903,316881,52630,164058,130904,509102,52811,218012,104598,256294,49152
2,Tedding Temple,Alma Valley East,21413,33423,99632,282782,61882,233307,185421,673693,67449,313138,130697,284248,61592
3,Techno Garden,Alma Valley East,50162,68556,53382,1619757,129247,66028,62009,112004,41347,52228,214597,44752,31044
4,Leighton,Alma Valley East,461,1043,1833,4382,1824,7187,4588,24974,989,18779,4193,25895,13131
5,Gorton Quarters,Alma Valley East,7687,14454,51778,166280,33171,130976,90086,413185,28560,225597,88295,246526,62398
6,Central,Alma Valley East,21389,46418,94166,551916,125108,160224,131428,420688,55076,195272,108332,185445,47788
7,Durdham Mews,Alma Valley East,13524,20683,35196,164545,25520,86148,66559,232579,21438,120058,46683,126027,30087
8,Denton Town,Alma Valley East,4755,11742,22490,129107,19481,56663,42906,187536,16340,81855,34513,86861,38707
9,Permbroke Corner,Alma Valley West,3552,9172,9904,38892,7239,34028,29792,70472,5189,49805,17662,69619,70677
10,Weslington,Alma Valley West,21985,48234,85252,283628,60856,243855,183903,790887,67537,371237,133228,397346,83533
11,Clifton Wick,Alma Valley West,5092,12174,9680,31155,8055,50331,38784,103458,6016,82997,19850,87128,74971
12,Cotham Heights,Alma Valley West,16234,33336,49290,261093,100334,130393,105654,270795,34452,157500,64297,149068,45964
13,Pebble Palace,Highland,128397,157422,122364,113118,31213,436817,402359,566833,81150,220512,195280,161992,91138
14,Tenna Court,Highland,2234,3353,5976,3986,2132,32486,27380,61238,5537,25446,13525,16928,14605
15,Slothwood,Highland,18409,33638,41979,38277,12788,192943,169947,317391,35849,119540,84387,105693,85819
16,Queens Mansion,Highland,34886,54227,94723,71244,27854,425202,353451,816897,77367,344563,217795,296094,174808
17,Meadow Hill,Highland,3298,9509,6426,6092,2454,41776,34364,69298,5687,29772,14051,17560,31011
18,Hopewell Harbor,Highland,0,0,498,157,0,996,839,8071,0,7130,498,11648,19969
19,Goldcrest Villas,Highland,20805,36377,50562,46796,17993,258627,208792,485508,47013,179055,118382,156854,81881
20,Grillbys Crest,Highland,1264,1745,3595,2962,1030,16683,10822,56899,2489,24635,6373,27976,39646
21,Lancer Gate,Highland,18020,25410,53478,39777,17400,253940,202613,574871,46626,250047,147312,205065,83675
22,Northfields Market,Midlands,9491,19872,47232,37330,16044,112570,92033,196790,30466,120686,50438,95554,129389
23,Alma Bridge,Midlands,86002,178420,365141,317392,230732,690018,557512,1137346,190132,749602,435626,498373,565588
24,Alma Junction,Midlands,9946,21195,29740,37806,13406,101138,83283,157374,24733,83191,38175,50651,71727
25,Bayes Valley,Midlands,4733,11920,19743,17229,7422,51585,40638,89752,13206,56659,23603,30533,68801
26,Readington,Midlands,7573,21371,19545,41236,9950,54677,48754,71532,13355,40147,25651,27499,37944
27,Alma Heath,Midlands,694,1339,1660,2912,1283,8242,6487,13144,1061,9729,2744,9232,26126
28,Alma Forest,Midlands,2846,8274,7125,12527,4513,30971,24226,43787,4085,31105,8171,22988,77519
29,Waltham Grove,South East,1687,1369,2739,3930,2986,15536,12138,26808,1237,24038,7043,22153,82724
30,Eton Gate,South East,5858,11733,21120,26453,11297,84875,68606,136071,18272,77378,28639,49189,130099
31,Aqua Bay,South East,1751,3740,4199,5212,3072,19369,13547,49780,5023,28328,8870,20075,47280
32,Oakfield Bush,South East,2739,3737,4804,9259,4061,33069,25046,42946,3583,31289,9018,16775,61886
33,Waterstone,South East,517,572,535,1594,841,5206,3363,10097,702,6844,1558,8947,20797
34,Storport,South East,699,1267,4588,3842,1657,10435,8216,21985,3304,14412,11336,13604,33046
35,Dressingham,South East,3217,6188,17223,13855,5930,45335,35227,69445,10624,47507,22957,26779,60063

,Zone,Region,S,A1,A2,B1,B2,C1,C2,D1,D2,E1,E2,F1,F2
0,Alington,Alma Valley East,144666,178454,188597,694441,117967,266277,236514,672494,90503,301606,164317,283323,50433
1,Twicken Meads,Alma Valley East,22169,56996,83903,316881,52630,164058,130904,509102,52811,218012,104598,256294,49152
2,Tedding Temple,Alma Valley East,21413,33423,99632,282782,61882,233307,185421,673693,67449,313138,130697,284248,61592
3,Techno Garden,Alma Valley East,50162,68556,53382,1619757,129247,66028,62009,112004,41347,52228,214597,44752,31044
4,Leighton,Alma Valley East,461,1043,1833,4382,1824,7187,4588,24974,989,18779,4193,25895,13131
5,Gorton Quarters,Alma Valley East,7687,14454,51778,166280,33171,130976,90086,413185,28560,225597,88295,246526,62398
6,Central,Alma Valley East,21389,46418,94166,551916,125108,160224,131428,420688,55076,195272,108332,185445,47788
7,Durdham Mews,Alma Valley East,13524,20683,35196,164545,25520,86148,66559,232579,21438,120058,46683,126027,30087
8,Denton Town,Alma Valley East,4755,11742,22490,129107,19481,56663,42906,187536,16340,81855,34513,86861,38707
9,Permbroke Corner,Alma Valley West,3552,9172,9904,38892,7239,34028,29792,70472,5189,49805,17662,69619,70677
10,Weslington,Alma Valley West,21985,48234,85252,283628,60856,243855,183903,790887,67537,371237,133228,397346,83533
11,Clifton Wick,Alma Valley West,5092,12174,9680,31155,8055,50331,38784,103458,6016,82997,19850,87128,74971
12,Cotham Heights,Alma Valley West,16234,33336,49290,261093,100334,130393,105654,270795,34452,157500,64297,149068,45964
13,Pebble Palace,Highland,128397,157422,122364,113118,31213,436817,402359,566833,81150,220512,195280,161992,91138
14,Tenna Court,Highland,2234,3353,5976,3986,2132,32486,27380,61238,5537,25446,13525,16928,14605
15,Slothwood,Highland,18409,33638,41979,38277,12788,192943,169947,317391,35849,119540,84387,105693,85819
16,Queens Mansion,Highland,34886,54227,94723,71244,27854,425202,353451,816897,77367,344563,217795,296094,174808
17,Meadow Hill,Highland,3298,9509,6426,6092,2454,41776,34364,69298,5687,29772,14051,17560,31011
18,Hopewell Harbor,Highland,0,0,498,157,0,996,839,8071,0,7130,498,11648,19969
19,Goldcrest Villas,Highland,20805,36377,50562,46796,17993,258627,208792,485508,47013,179055,118382,156854,81881
20,Grillbys Crest,Highland,1264,1745,3595,2962,1030,16683,10822,56899,2489,24635,6373,27976,39646
21,Lancer Gate,Highland,18020,25410,53478,39777,17400,253940,202613,574871,46626,250047,147312,205065,83675
22,Northfields Market,Midlands,9491,19872,31522,37330,16930,112570,92033,192747,30466,130255,50438,107178,127066
23,Alma Bridge,Midlands,66439,170608,166241,310674,178399,637716,520330,1135994,166912,904867,374053,713137,655141
24,Alma Junction,Midlands,9946,21195,23175,37806,13694,101138,83283,155087,24733,87277,38175,55841,71019
25,Bayes Valley,Midlands,4719,11907,14300,17181,7524,51462,40529,88472,13227,61047,23610,33729,68118
26,Readington,Midlands,7573,21371,16290,41236,10094,54677,48754,69459,13355,42330,25651,30790,37650
27,Alma Heath,Midlands,694,1339,1615,2912,1283,8242,6487,13130,1061,9760,2744,9259,26126
28,Alma Forest,Midlands,2833,8230,5592,12524,4526,30959,24209,43401,4082,32251,8169,23884,77478
29,Waltham Grove,South East,1687,1369,2714,3930,2986,15536,12138,26800,1237,24055,7043,22169,82724
30,Eton Gate,South East,5858,11733,16945,26453,11436,84875,68606,134522,18272,80704,28639,51950,129599
31,Aqua Bay,South East,1751,3740,3186,5212,3072,19369,13547,49508,5023,29012,8870,20767,47186
32,Oakfield Bush,South East,2739,3737,4751,9259,4061,33069,25046,42929,3583,31323,9018,16810,61886
33,Waterstone,South East,517,572,494,1594,841,5206,3363,10083,702,6871,1558,8974,20797
34,Storport,South East,699,1267,3310,3842,1755,10435,8216,21786,3304,14990,11336,14598,32855
35,Dressingham,South East,3217,6188,11342,13855,6119,45335,35227,67184,10624,52431,22957,30363,59502